name: generate-snake-game-from-github-contribution-grid
description: Generates a snake game from a GitHub user's contributions grid. Outputs the animation as a GIF or SVG.
author: platane

on:  # Specify the event that triggers the action
  push:
    branches:
      - main  # Specify the branch(es) on which the action should run

runs:
  using: "docker"
  image: "docker://platane/snk@sha256:1c8a0b51a75ad8cf36b7defddd2187bdbb92bbbb5521a9e6cc5df795b00fc590"

inputs:
  github_user_name:
    description: "GitHub user name for which the contribution grid will be used."
    required: true
  github_token:
    description: "GitHub token used to fetch the contribution calendar. Defaults to the action token if not provided."
    required: false
    default: ${{ github.token }}
  outputs:
    required: false
    description: |
      List of files to generate, one per line. Each output can be customized with query string options.

      Supported query string options:
      - palette: A preset of colors, one of [github, github-dark, github-light]
      - color_snake: Color of the snake in the game
      - color_dots: Comma-separated list of dot colors. The first color represents 0 contributions, followed by low to high contributions.
                    Exactly 5 colors are required.

      Example:
        outputs: |
          dark.svg?palette=github-dark&color_snake=blue
          light.svg?color_snake=#7845ab
          ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
