  - name: Generate Snake Game from GitHub Contribution Grid
    uses: Platane/snk@v3
    with:
      github_user_name: ${{ github.repository_owner }}
      outputs: |
        dist/github-snake.svg
        dist/github-snake-dark.svg?palette=github-dark
        dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

  - name: Push to GitHub
    uses: EndBug/add-and-commit@v9
    with:
      branch: main
      message: 'Generate Contribution Snake'

  - name: Deploy to GitHub Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./dist

# <picture>
#   <source media="(prefers-color-scheme: dark)" srcset="github-snake-dark.svg" />
#   <source media="(prefers-color-scheme: light)" srcset="github-snake.svg" />
#   <img alt="github-snake" src="github-snake.svg" />
# </picture>

  - name: Setup Node.js environment
    uses: actions/setup-node@v4.0.4
    with:
      node-version: '20.x'  # Required: specify Node.js version to install
      cache: 'npm'          # Optional: specify the package manager for caching (npm, yarn, pnpm)
      always-auth: false    # Optional: set always-auth to false or true as needed
      check-latest: false   # Optional: set this option to true if you want the action to check for the latest version
      registry-url: 'https://registry.npmjs.org/'  # Optional: specify registry URL if needed
      cache-dependency-path: 'package-lock.json'   # Optional: path to the dependency file
